export const UserProfileNavigationConstraints='UserProfileNavigationConstraints'
export const CartAddAction='CartAddAction'
export const LoginStatusConstraints='LoginStatusConstraints'
export const SellerTabAccActionConstraints='SellerTabAccActionConstraints'